### ISSUE TITLE
Can't reproduce the performance on real_example charlie.png

### ISSUE THREAD

**Issue by back2yes** [assafshocher/ZSSR#8]
Hi, I ran the code `run_ZSSR_single_input.py` on charlie.png but the results seemed to be about the same with EDSR, this is what I ran:

```
python run_ZSSR_single_input.py real_example/charlie.png 0 0 0 X2_GRADUAL_IDEAL_CONF output_real
```

I am wondering if I misunderstood the code?

**Comment by assafshocher** [comment]
Hi,
You ran a real image (non-ideal) with ideal conf.
To run on this particular image, just run: 
`python run_ZSSR.py X2_REAL_CONF`

**Comment by back2yes** [comment]
Thank you for your help, I tried `X2_REAL_CONF` but the result seemed to be the same

This is what I get https://pbs.twimg.com/media/DsKk6i7VsAAL8XW.jpg:large, could you help to judge if this result is correct?

**Comment by assafshocher** [comment]
Hi,
please make sure the kernel .mat file exists and that you don't get a message that no kernel is used when running.

**Comment by CurryYuan** [comment]
Same problem here.

**Comment by assafshocher** [comment]
@back2yes, @CurryYuan 
First, which Python version do you use? ZSSR is made for py2 (unfortunately). If you run it with py3, and modified, you may have problems with some divisions ( / ) in the resizing. This is slovable and stable py3 versions exist. let me know.
Second, have you seen the kernel loaded during the ZSSR run? 
When it is loaded, [this line](https://github.com/assafshocher/ZSSR/blob/master/run_ZSSR.py#L42) prints the kernel file path.
However, if no kernel supplied then [this line](https://github.com/assafshocher/ZSSR/blob/master/run_ZSSR.py#L42) prints "no kernel loaded".

**Comment by Intro1997** [comment]
Hello, I run your code in py3 and I do have the divsions (/) problem. After using (//) instead of (/) I got a poor result. And after changing my environment to py2, I try to run `python run_ZSSR.py X2_REAL_CONF` but I get the following error:
Traceback (most recent call last):
  File "run_ZSSR.py", line 4, in <module>
    from utils import prepare_result_dir
  File "/Users/outro/Downloads/ZSSR/utils.py", line 1, in <module>
    import numpy as np
  File "/usr/local/lib/python2.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/usr/local/lib/python2.7/site-packages/numpy/core/__init__.py", line 123, in <module>
    from . import _dtype_ctypes
  File "/usr/local/lib/python2.7/site-packages/numpy/core/_dtype_ctypes.py", line 25, in <module>
    import _ctypes
ImportError: dlopen(/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_ctypes.so, 2): Symbol not found: __PySlice_AdjustIndices
  Referenced from: /usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_ctypes.so
  Expected in: flat namespace
 in /usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_ctypes.so
I don't known how to get it work.
